### ISSUE TITLE
[Feature] Keywords should be scoped by users

### ISSUE THREAD

**Issue by longnd** [giangbimin/gscaper#12]
## Issue
The current DB design has some limitations:
https://github.com/giangbimin/gscaper/blob/7a5ab2344947676b575d505e3c2eaf0f55cdd1f2/db/schema.rb#L45-L65

- Search results are not scoped by users (because they share the same keyword record)
- Even for the same user, each keyword is only uploaded once.

However, the fact is that even for the same keyword, the search results can change each time (even when performed by the same user in the same geolocation) or be completely different (if performed in a different geolocation, e.g., a user in Vietnam and a user in the UK searching for hotels will yield different results).

## Expected
- Search results are scoped by users
- Even for the same user, they can upload the same keyword multiple time, each can have different search result

**Comment by giangbimin** [comment]
@longnd 
- actually for the first time i was not expect for same keyword, the search results can change each time. (not enough to understand the scope of the spec)
- have a reason for the design here is cache old request and it don[t have to recreate a request again for same keyword of all user

### Update

[ ] Search results are scoped by users
[ ] Even for the same user, they can upload the same keyword multiple time, each can have different search result

###  next step: 

#### redesign db
- add table ScrapperSession

```
- user: references , content: "text"
```
- remove table user_keywords
- add `scrapper_session_id` to `keywords`

##### Refactor Service
- use function `insert_all` to create keywords after create `scrapper_session`

**Comment by giangbimin** [comment]
@longnd 
- i've been created a fix pr for this problems

https://github.com/giangbimin/gscaper/pull/20
