### ISSUE TITLE
 Follow Design Pattern for Services

### ISSUE THREAD

**Issue by longnd** [giangbimin/gscaper#13]
## Issue
While it's great that the business logic has been extracted to multiple Plain Old Ruby Objects (PORO) such as services, example:
- [keyword_scraper_service.rb](https://github.com/giangbimin/gscaper/blob/main/app/services/job/keyword_scraper_service.rb)
the current structure of these classes does not follow the standard design patterns.
- [csv_keywords_parser_service.rb](https://github.com/giangbimin/gscaper/blob/main/app/services/csv_keywords_parser_service.rb)

The current structure of these classes does not follow the standard naming convention of the design patterns

Service objects are expected to have only one public method `call` (not `execute`):
```
class SomeService
  def initialize(*args) do 
    #...
  end

  def call do
    #...
  end

  private

  # other methods
end
```

Some articles for references:
- https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial
- https://dev.to/joker666/ruby-on-rails-pattern-service-objects-b19

**Comment by giangbimin** [comment]
@longnd 
absolutely, i updated the convention of code and refactor it with a PR

https://github.com/giangbimin/gscaper/pull/21/files
