### ISSUE TITLE
[Feature] Lack of a way for users to logout

### ISSUE THREAD

**Issue by longnd** [giangbimin/gscaper#14]
## Issue
The authentication system is powered by Devise, which has built-in support for logging-out feature, but the application does not implement it, leaving the user without a way to logout

## Expected
The users should be able to logout from the application.

**Comment by giangbimin** [comment]
- actually i've already implement it but it's not included in the scope so im not create PR for this
@longnd 
[this is the PR to add logout feature](https://github.com/giangbimin/gscaper/pull/18/)
