### ISSUE TITLE
[Question] How the API consumer can refresh the access token

### ISSUE THREAD

**Issue by longnd** [giangbimin/gscaper#17]
## Issue
Given the Login API only return the access token, how can the API consumer refresh it when the token expire, I assume the client needs to call the login API again to get a new token?
<img width="933" alt="image" src="https://github.com/giangbimin/gscaper/assets/1896814/36f183c1-71b6-48c9-b84a-99941875e16e">

Also, a relevant question: were the APIs implemented follow any standard specification, e.g. [JSON API](https://jsonapi.org/). It doesn't seem to be the case.

**Comment by giangbimin** [comment]
@longnd 
actually the spec not include the logic to create refresh token,
i ll create a end-point for this

- there are some checklist to implement/ refactor for the next step

[] endpoint `POST api/refresh`
[] expired time of jwt: 15 mins
[] expired time of refresh token:  7 days
[] add refresh token to `api/login` response
[] add identify key to block old jwt/refresh token and add it to payload, save key in redis, if identify key(with exp) not exist in redis, we block it

- addition
[] add limit-rate to each session to cover many request in a minutes

**Comment by giangbimin** [comment]
# PR:

https://github.com/giangbimin/gscaper/pull/19

**Comment by giangbimin** [comment]
> were the APIs implemented follow any standard specification, e.g. [JSON API](https://jsonapi.org/). It doesn't seem to be the case.

### i plain to use this gem for easy to implement

`gem 'active_model_serializers'`

it's help me to easy to serializers data as JSON API format

then create 

```
class KeywordSerializer < ActiveModel::Serializer
  attributes :id, :content, :status, :total_link, :total_result, :total_ad, :html_code
end


```

apply to controller

```
render json: current_user.keywords
```

### Addition to create documentation for api

`gem 'apipie-rails '`

**Comment by giangbimin** [comment]
@longnd 

i created a pull request to implement the [JSON API](https://jsonapi.org/). standard for api
but i have not create a documentation for it right now

https://github.com/giangbimin/gscaper/pull/21/files
